package com.employee.app.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.employee.app.domain.Employee;
import com.employee.app.repository.EmployeeRepository;
import com.employee.app.service.EmployeeService;
@Controller
public class EmployeeController {
	
	@Autowired
	//the bean which is auto-generated by Spring
	private EmployeeService employeeService;

	@GetMapping("/login")
	public String showLoginForm(Model model) {
		return "login";
	}

	//display list of employees
	@GetMapping("/")
	public String viewHomePage(Model model) {

		model.addAttribute("listEmployees", employeeService.getAllEmployees());

		return "index";
	}

	//showNewEmployeeForm
	@GetMapping("/AddEmployee")
	public String AddEmployee(Model model) {
		Employee employee = new Employee();
		model.addAttribute("employee", employee);

		return "addEmp";
	}

	//add an employee
	@PostMapping("/saveEmployee")
	public String saveEmployee(@ModelAttribute("employee") Employee employee) {

		employeeService.saveEmployee(employee);

		return "redirect:/";
	}

	//show update form
	@GetMapping("/showFormForUpdate/{id}")
	public String showUpdateForm(@PathVariable Integer id, Model model) {

		Employee employee = employeeService.getEmployeeById(id);

		model.addAttribute("employee", employee);
		return "updateEmp";
	}

	//delete the employee by id
	@GetMapping("/delete/{id}")
	public String deleteEmployeeById(@PathVariable Integer id, Model model) {
		employeeService.deleteEmployeeById(id);

		return "redirect:/";
	}
}
